### ISSUE TITLE
Add new phone number.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Oranit-Uzan-Milestones-Site#4]
She asked to add her own phone number to the site as well. Michael needs to design something.

**Comment by iliyaM** [comment]
He said make it standard button green with phone number

בתאריך 11 בספט' 2016 19:16,‏ "Mladen Mijatov" notifications@github.com
כתב:

**Comment by iliyaM** [comment]
![capture](https://cloud.githubusercontent.com/assets/20294485/18427270/af57b982-78cf-11e6-97b7-9747b5fd0a34.JPG)

added header footer & mobile
